name: Get LwM2M type definition

on:
  push:

  workflow_dispatch:

jobs:
  getTypes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: execute conversion
        run: npx tsx src/main.ts
