name: Get LwM2M type definition

on:
  push:

  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Create folders
        run: mkdir ./LWM2M && cd ./LWM2M && mkdir XML && mkdir JSON && mkdir TS

      - name: Clone LwM2M repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: "OpenMobileAlliance"
          repository: "lwm2m-registry"

      - name: Logs
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd ./LWM2M/XML/lwm2m-registry
          ls -la
