name: Get LwM2M type definition

on:
  push:

  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Create folders
        run: mkdir ./LWM2M && cd ./LWM2M && mkdir XML && mkdir JSON && mkdir TS
